<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EscolasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Desativa a verificação de chaves estrangeiras temporariamente
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('escolas')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Lista de escolas
        $escolas = [
            ['id' => 1, 'nome' => 'E.M.E.I. ADJALVA FERREIRA LIMA', 'codigo_escola' => 'ESC001'],
            ['id' => 2, 'nome' => 'E.M.E.I. AMÉLIA BORGES', 'codigo_escola' => 'ESC002'],
            ['id' => 3, 'nome' => 'E.M.E.I. AMÉLIA DUARTE', 'codigo_escola' => 'ESC003'],
            ['id' => 4, 'nome' => 'E.M.E.I. AMÉRICO TANURY - ABÓBORA', 'codigo_escola' => 'ESC004'],
            ['id' => 5, 'nome' => 'E.M.E.I. ANA MARIA MORGADO CHAVES', 'codigo_escola' => 'ESC005'],
            ['id' => 6, 'nome' => 'E.M.E.I. ANNA HILDA LEITE FARIAS', 'codigo_escola' => 'ESC006'],
            ['id' => 7, 'nome' => 'E.M.E.I. ARCENIO JOSÉ DA SILVA', 'codigo_escola' => 'ESC007'],
            ['id' => 8, 'nome' => 'E.M.E.I. ARLINDA ALVES VARJÃO', 'codigo_escola' => 'ESC008'],
            ['id' => 9, 'nome' => 'E.M.E.I. BEATRIZ ANGÉLICA MOTA', 'codigo_escola' => 'ESC009'],
            ['id' => 10, 'nome' => 'E.M.E.I. BOLIVAR SANTANA', 'codigo_escola' => 'ESC010'],
            ['id' => 11, 'nome' => 'E.M.E.I. BOM JESUS DOS NAVEGANTES', 'codigo_escola' => 'ESC011'],
            ['id' => 12, 'nome' => 'E.M.E.I. CAIC MISAEL AGUILAR', 'codigo_escola' => 'ESC012'],
            ['id' => 14, 'nome' => 'E.M.E.I. DILMA CALMON DE OLIVEIRA', 'codigo_escola' => 'ESC013'],
            ['id' => 15, 'nome' => 'E.M.E.I. EDIVÂNIA SANTOS CARDOSO', 'codigo_escola' => 'ESC014'],
            ['id' => 16, 'nome' => 'E.M.E.I. ELEOTÉRIO SOARES FONSÊCA', 'codigo_escola' => 'ESC015'],
            ['id' => 17, 'nome' => 'E.M.E.I. GENTIL DAMÁSIO DO NASCIMENTO', 'codigo_escola' => 'ESC016'],
            ['id' => 18, 'nome' => 'EXTENSAO - E.M.E.I. GENTIL DAMASIO DO NASCIMENTO', 'codigo_escola' => 'ESC017'],
            ['id' => 19, 'nome' => 'E.M.E.I. HERBET MOUSE RODRIGUES', 'codigo_escola' => 'ESC018'],
            ['id' => 20, 'nome' => 'E.M.E.I. IRMÃ REDENTA', 'codigo_escola' => 'ESC019'],
            ['id' => 21, 'nome' => 'E.M.E.I. JANDIRA BORGES', 'codigo_escola' => 'ESC020'],
            ['id' => 22, 'nome' => 'E.M.E.I. LENI LOPES DE ARAÚJO SANTOS', 'codigo_escola' => 'ESC021'],
            ['id' => 23, 'nome' => 'E.M.E.I. LUANA DA SILVA NASCIMENTO', 'codigo_escola' => 'ESC022'],
            ['id' => 24, 'nome' => 'E.M.E.I. LUZINETE DE OLIVEIRA', 'codigo_escola' => 'ESC023'],
            ['id' => 25, 'nome' => 'E.M.E.I. MANOEL ALVES DA MOTA', 'codigo_escola' => 'ESC024'],
            ['id' => 26, 'nome' => 'E.M.E.I. MARIA FERREIRA DE SOUZA', 'codigo_escola' => 'ESC025'],
            ['id' => 27, 'nome' => 'E.M.E.I. MARIA HELENA DA SILVA PEREIRA', 'codigo_escola' => 'ESC026'],
            ['id' => 28, 'nome' => 'E.M.E.I. MARIA HOZANA NUNES', 'codigo_escola' => 'ESC027'],
            ['id' => 29, 'nome' => 'E.M.E.I. MARIA JÚLIA RODRIGUES TANURI', 'codigo_escola' => 'ESC028'],
            ['id' => 30, 'nome' => 'E.M.E.I. MARIÁ VIANA TANURI', 'codigo_escola' => 'ESC029'],
            ['id' => 31, 'nome' => 'EXTENSAO - E.M.E.I. MARIA VIANA TANURI', 'codigo_escola' => 'ESC030'],
            ['id' => 32, 'nome' => 'E.M.E.I. NAILDE DE SOUZA COSTA', 'codigo_escola' => 'ESC031'],
            ['id' => 33, 'nome' => 'E.M.E.I. NOSSA SENHORA DAS GROTAS - CARNAÍBA', 'codigo_escola' => 'ESC032'],
            ['id' => 34, 'nome' => 'E.M.E.I. NOSSO SENHOR DOS AFLITOS', 'codigo_escola' => 'ESC033'],
            ['id' => 35, 'nome' => 'E.M.E.I. PASSAGEM DO SARGENTO', 'codigo_escola' => 'ESC034'],
            ['id' => 36, 'nome' => 'E.M.E.I. PASTOR MANOEL MARQUES DE SOUZA', 'codigo_escola' => 'ESC035'],
            ['id' => 37, 'nome' => 'E.M.E.I. PREFEITO APRÍGIO DUARTE', 'codigo_escola' => 'ESC036'],
            ['id' => 38, 'nome' => 'E.M.E.I. ADELAIDE MOREIRA BISPO', 'codigo_escola' => 'ESC037'],
            ['id' => 39, 'nome' => 'E.M.E.I. PROFª HELOISA HELENA BENEVIDES FARIAS', 'codigo_escola' => 'ESC038'],
            ['id' => 40, 'nome' => 'E.M.E.I. PROFª JOANA RAMOS', 'codigo_escola' => 'ESC039'],
            ['id' => 41, 'nome' => 'E.M.E.I. MARIA SUELY MEDRADO ARAÚJO', 'codigo_escola' => 'ESC040'],
            ['id' => 42, 'nome' => 'E.M.E.I. VANDA GUERRA', 'codigo_escola' => 'ESC041'],
            ['id' => 44, 'nome' => '02 DE JULHO', 'codigo_escola' => 'ESC042'],
            ['id' => 45, 'nome' => '15 DE JULHO', 'codigo_escola' => 'ESC043'],
            ['id' => 46, 'nome' => '25 DE JULHO', 'codigo_escola' => 'ESC044'],
            ['id' => 47, 'nome' => 'AMÉRICO TANURI - JUNCO', 'codigo_escola' => 'ESC045'],
            ['id' => 48, 'nome' => 'AMÉRICO TANURI - MANIÇOBA', 'codigo_escola' => 'ESC046'],
            ['id' => 49, 'nome' => 'ANÁLIA BARBOSA DE SOUZA', 'codigo_escola' => 'ESC047'],
            ['id' => 50, 'nome' => 'ANTONIO FRANCISCO DE OLIVEIRA', 'codigo_escola' => 'ESC048'],
            ['id' => 51, 'nome' => 'ARGEMIRO JOSE DA CRUZ', 'codigo_escola' => 'ESC049'],
            ['id' => 52, 'nome' => 'BOM JESUS - BARAÚNA', 'codigo_escola' => 'ESC050'],
            ['id' => 53, 'nome' => 'BOM JESUS - NH1', 'codigo_escola' => 'ESC051'],
            ['id' => 54, 'nome' => 'CAIC - MISAEL AGUILAR', 'codigo_escola' => 'ESC052'],
            ['id' => 55, 'nome' => 'CAXANGÁ', 'codigo_escola' => 'ESC053'],
            ['id' => 56, 'nome' => 'CELSO CAVALCANTE DE CARVALHO', 'codigo_escola' => 'ESC054'],
            ['id' => 57, 'nome' => 'CENTRO SOCIAL URBANO - CSU', 'codigo_escola' => 'ESC055'],
            ['id' => 58, 'nome' => 'CORAÇÃO DE JESUS - JUREMA VERMELHA', 'codigo_escola' => 'ESC056'],
            ['id' => 59, 'nome' => 'CORAÇÃO DE JESUS - SERRA DA MADEIRA', 'codigo_escola' => 'ESC057'],
            ['id' => 60, 'nome' => 'PROMENOR', 'codigo_escola' => 'ESC058'],
            ['id' => 61, 'nome' => 'E.M.E.I. NÉLIA DE SOUZA COSTA', 'codigo_escola' => 'ESC059'],
            ['id' => 62, 'nome' => 'JATOBÁ', 'codigo_escola' => 'ESC060'],
            ['id' => 63, 'nome' => 'PONTAL', 'codigo_escola' => 'ESC061'],
            ['id' => 64, 'nome' => 'PEDRO DIAS', 'codigo_escola' => 'ESC062'],
            ['id' => 65, 'nome' => 'E.M.T.I. PROFª IRACEMA PEREIRA DA PAIXÃO', 'codigo_escola' => 'ESC063'],
            ['id' => 66, 'nome' => 'DEPUTADO RAIMUNDO DA CUNHA LEITE', 'codigo_escola' => 'ESC064'],
            ['id' => 67, 'nome' => 'DOM AVELAR BRANDAO VILELA', 'codigo_escola' => 'ESC065'],
            ['id' => 69, 'nome' => 'DOUTOR EDSON RIBEIRO', 'codigo_escola' => 'ESC066'],
            ['id' => 70, 'nome' => 'DURVAL BARBOSA DA CUNHA', 'codigo_escola' => 'ESC067'],
            ['id' => 71, 'nome' => 'EDUCANDÁRIO JOÃO XXIII', 'codigo_escola' => 'ESC068'],
            ['id' => 72, 'nome' => 'ELISEU SANTOS', 'codigo_escola' => 'ESC069'],
            ['id' => 73, 'nome' => 'ESTAÇÃO DO SABER JOSÉ CARLOS TANURI', 'codigo_escola' => 'ESC070'],
            ['id' => 74, 'nome' => 'EURÍDICE RIBEIRO VIANA', 'codigo_escola' => 'ESC071'],
            ['id' => 75, 'nome' => 'FAMÍLIA UNIDA', 'codigo_escola' => 'ESC072'],
            ['id' => 76, 'nome' => 'HELENA CELESTINO MAGALHÃES', 'codigo_escola' => 'ESC073'],
            ['id' => 77, 'nome' => 'JOÃO DIAS FERREIRA', 'codigo_escola' => 'ESC074'],
            ['id' => 78, 'nome' => 'JOÃO NEVES DE ALMEIDA', 'codigo_escola' => 'ESC075'],
            ['id' => 79, 'nome' => 'JOCA DE SOUZA OLIVEIRA', 'codigo_escola' => 'ESC076'],
            ['id' => 80, 'nome' => 'JOSÉ DE AMORIM', 'codigo_escola' => 'ESC077'],
            ['id' => 81, 'nome' => 'JOSÉ PADILHA DE SOUZA', 'codigo_escola' => 'ESC078'],
            ['id' => 82, 'nome' => 'JUDITE LEAL COSTA', 'codigo_escola' => 'ESC079'],
            ['id' => 83, 'nome' => 'LINDAURA MARIA DE JESUS', 'codigo_escola' => 'ESC080'],
            ['id' => 84, 'nome' => 'LÚCIA CARMEM SOBREIRA', 'codigo_escola' => 'ESC081'],
            ['id' => 85, 'nome' => 'LUDGERO DE SOUZA COSTA', 'codigo_escola' => 'ESC082'],
            ['id' => 86, 'nome' => 'PROFº LUIS CURSINO DA FRANÇA CARDOSO', 'codigo_escola' => 'ESC083'],
            ['id' => 87, 'nome' => 'MANDACARU', 'codigo_escola' => 'ESC084'],
            ['id' => 88, 'nome' => 'MANOEL DE SOUZA BONFIM', 'codigo_escola' => 'ESC085'],
            ['id' => 89, 'nome' => 'MANOEL GOMES MARTINS', 'codigo_escola' => 'ESC086'],
            ['id' => 90, 'nome' => 'MANOEL LUIZ DA SILVA', 'codigo_escola' => 'ESC087'],
            ['id' => 91, 'nome' => 'MANOEL NUNES AMORIM', 'codigo_escola' => 'ESC088'],
            ['id' => 92, 'nome' => 'MARIA DO CARMO SÁ NOGUEIRA', 'codigo_escola' => 'ESC089'],
            ['id' => 93, 'nome' => 'MARIA MONTEIRO BACELAR', 'codigo_escola' => 'ESC090'],
            ['id' => 94, 'nome' => 'MARIANO RODRIGUES DE SOUZA', 'codigo_escola' => 'ESC091'],
            ['id' => 95, 'nome' => 'MIGUEL ÂNGELO DE SOUZA', 'codigo_escola' => 'ESC092'],
            ['id' => 96, 'nome' => 'NOSSA SENHORA DAS GROTAS - BOQUEIRÃO', 'codigo_escola' => 'ESC093'],
            ['id' => 97, 'nome' => 'NOSSA SENHORA DAS GROTAS-SEDE', 'codigo_escola' => 'ESC094'],
            ['id' => 98, 'nome' => 'NOSSA SENHORA RAINHA DOS ANJOS', 'codigo_escola' => 'ESC095'],
            ['id' => 99, 'nome' => 'OSORIO TELES DE MENEZES', 'codigo_escola' => 'ESC096'],
            ['id' => 100, 'nome' => 'PAULO FREIRE', 'codigo_escola' => 'ESC097'],
            ['id' => 101, 'nome' => 'PAULO VI', 'codigo_escola' => 'ESC098'],
            ['id' => 102, 'nome' => 'PREFEITO APRÍGIO DUARTE', 'codigo_escola' => 'ESC099'],
            ['id' => 103, 'nome' => 'PRESIDENTE TANCREDO NEVES', 'codigo_escola' => 'ESC100'],
            ['id' => 104, 'nome' => 'EXTENSAO - E.M.E.I. LUZINETE DE OLIVEIRA/HELENA ARAÚJO PINHEIRO', 'codigo_escola' => 'ESC101'],
            ['id' => 105, 'nome' => 'PROFª MATILDE COSTA MEDRADO', 'codigo_escola' => 'ESC102'],
            ['id' => 106, 'nome' => 'PROFº PEDRO RAIMUNDO RODRIGUES REGO', 'codigo_escola' => 'ESC103'],
            ['id' => 107, 'nome' => 'PROFª DINORAH ALBERNAZ MELO DA SILVA', 'codigo_escola' => 'ESC104'],
            ['id' => 108, 'nome' => 'PROFº CARLOS DA COSTA SILVA', 'codigo_escola' => 'ESC105'],
            ['id' => 109, 'nome' => 'PROFº JOSÉ PEREIRA DA SILVA', 'codigo_escola' => 'ESC106'],
            ['id' => 110, 'nome' => 'PROFª ANTONILA DA FRANÇA CARDOSO', 'codigo_escola' => 'ESC107'],
            ['id' => 111, 'nome' => 'PROFª ATANILHA LUZ ARAÚJO', 'codigo_escola' => 'ESC108'],
            ['id' => 112, 'nome' => 'PROFª BERNADETE BRAGA', 'codigo_escola' => 'ESC109'],
            ['id' => 113, 'nome' => 'PROFª CARMEM COSTA SANTOS', 'codigo_escola' => 'ESC110'],
            ['id' => 114, 'nome' => 'PROFª CRENILDES LUIZ BRANDÃO', 'codigo_escola' => 'ESC111'],
            ['id' => 115, 'nome' => 'PROFª EDUALDINA DAMÁSIO', 'codigo_escola' => 'ESC112'],
            ['id' => 116, 'nome' => 'GRACIOSA XAVIER RAMOS GOMES', 'codigo_escola' => 'ESC113'],
            ['id' => 117, 'nome' => 'PROFª GUIOMAR LUSTOSA RODRIGUES', 'codigo_escola' => 'ESC114'],
            ['id' => 118, 'nome' => 'PROFª HAYDÉE FONSECA FALCÃO', 'codigo_escola' => 'ESC115'],
            ['id' => 119, 'nome' => 'HELENA ARAÚJO PINHEIRO', 'codigo_escola' => 'ESC116'],
            ['id' => 120, 'nome' => 'PROFª IRACY NUNES DA SILVA', 'codigo_escola' => 'ESC117'],
            ['id' => 121, 'nome' => 'PROFª LEOPOLDINA LEAL', 'codigo_escola' => 'ESC118'],
            ['id' => 122, 'nome' => 'MARIA AMÉLIA DE SOUZA OLIVEIRA', 'codigo_escola' => 'ESC119'],
            ['id' => 123, 'nome' => 'PROFª MARIA DE LOURDES DUARTE', 'codigo_escola' => 'ESC120'],
            ['id' => 124, 'nome' => 'PROFª MARIA FRANCA PIRES', 'codigo_escola' => 'ESC121'],
            ['id' => 125, 'nome' => 'PROFª MARIA JOSÉ LIMA DA ROCHA', 'codigo_escola' => 'ESC122'],
            ['id' => 126, 'nome' => 'MARIA JULIA RODRIGUES TANURI', 'codigo_escola' => 'ESC123'],
            ['id' => 127, 'nome' => 'C.R.A. PROFª MAZZARELLO CAVALCANTI REIS DA ROCHA', 'codigo_escola' => 'ESC124'],
            ['id' => 128, 'nome' => 'PROFª OSCARLINA TANURI', 'codigo_escola' => 'ESC125'],
            ['id' => 129, 'nome' => 'PROFª TEREZINHA FERREIRA DE OLIVEIRA', 'codigo_escola' => 'ESC126'],
            ['id' => 130, 'nome' => 'RAIMUNDO CLEMENTINO DE SOUZA', 'codigo_escola' => 'ESC127'],
            ['id' => 131, 'nome' => 'RAIMUNDO MEDRADO PRIMO', 'codigo_escola' => 'ESC128'],
            ['id' => 132, 'nome' => 'RURAL DE MASSAROCA - ERUM', 'codigo_escola' => 'ESC129'],
            ['id' => 133, 'nome' => 'E.M.R.T.I. SÃO JOSÉ', 'codigo_escola' => 'ESC130'],
            ['id' => 134, 'nome' => 'SANTA INÊS', 'codigo_escola' => 'ESC131'],
            ['id' => 135, 'nome' => 'SANTA TEREZINHA', 'codigo_escola' => 'ESC132'],
            ['id' => 136, 'nome' => 'SANTO ANTÔNIO', 'codigo_escola' => 'ESC133'],
            ['id' => 137, 'nome' => 'SÃO FRANCISCO DE ASSIS - NH2', 'codigo_escola' => 'ESC134'],
            ['id' => 138, 'nome' => 'SÃO FRANCISCO DE ASSIS - MULUNGÚ', 'codigo_escola' => 'ESC135'],
            ['id' => 139, 'nome' => 'SÃO JOSÉ', 'codigo_escola' => 'ESC136'],
            ['id' => 140, 'nome' => 'SÃO SEBASTIÃO', 'codigo_escola' => 'ESC137'],
            ['id' => 141, 'nome' => 'VEREADOR AMADEUS DAMÁSIO', 'codigo_escola' => 'ESC138'],
            ['id' => 143, 'nome' => 'EXTENSAO - MARIA MONTEIRO BACELAR', 'codigo_escola' => 'ESC139'],
            ['id' => 144, 'nome' => 'E.M.E.I. MARIA DE LOURDES DO VALLE ALMEIDA', 'codigo_escola' => 'ESC140'],
            ['id' => 145, 'nome' => 'EXTENSAO - BOLIVAR SANTANA', 'codigo_escola' => 'ESC141'],
            ['id' => 146, 'nome' => 'EXTENSAO E.M.E.I. NAILDE COSTA / JUA CRESCE MAIS / CENTENARIO', 'codigo_escola' => 'ESC142'],
            ['id' => 147, 'nome' => 'EXTENSAO - PRESIDENTE TANCREDO NEVES', 'codigo_escola' => 'ESC143'],
            ['id' => 148, 'nome' => 'EXTENSAO - PROFª EDUALDINA DAMÁSIO', 'codigo_escola' => 'ESC144'],
            ['id' => 149, 'nome' => 'EXTENSAO - PROFº PEDRO RAIMUNDO RODRIGUES REGO', 'codigo_escola' => 'ESC145'],
            ['id' => 150, 'nome' => 'EXTENSAO - RAIMUNDO MEDRADO PRIMO', 'codigo_escola' => 'ESC146'],
            ['id' => 151, 'nome' => 'EXTENSAO - PONTAL', 'codigo_escola' => 'ESC147'],
            ['id' => 152, 'nome' => 'EXTENSAO - E.M.E.I. HERBET MOUSE RODRIGUES', 'codigo_escola' => 'ESC148'],
            ['id' => 153, 'nome' => 'EXTENSAO - DOM AVELAR BRANDAO VILELA', 'codigo_escola' => 'ESC149'],
            ['id' => 154, 'nome' => 'EXTENSAO - JOÃO DIAS FERREIRA', 'codigo_escola' => 'ESC150'],
            ['id' => 155, 'nome' => 'EXTENSAO - E.M.E.I. PREFEITO APRÍGIO DUARTE', 'codigo_escola' => 'ESC151'],
            ['id' => 156, 'nome' => 'EXTENSAO - E.M.E.I. ADELAIDE MOREIRA BISPO', 'codigo_escola' => 'ESC152'],
            ['id' => 157, 'nome' => 'EXTENSAO - DEPUTADO RAIMUNDO DA CUNHA LEITE', 'codigo_escola' => 'ESC153'],
            ['id' => 158, 'nome' => 'E.M.E.I. INGRIDY VITÓRIA GOMES DA SILVA', 'codigo_escola' => 'ESC154'],
            ['id' => 159, 'nome' => 'EXTENSAO - E.M.E.I. DILMA CALMON DE OLIVEIRA', 'codigo_escola' => 'ESC155'],
            ['id' => 160, 'nome' => 'EXTENSAO - E.M.T.I. PROFª IRACEMA PEREIRA DA PAIXÃO', 'codigo_escola' => 'ESC156'],
        ];

        // Inserir escolas no banco de dados
        DB::table('escolas')->insert($escolas);
    }
}